// @ts-nocheck
import React from 'react';
import { Link } from 'react-router-dom';

export function Privacy(props){
    return <React.Fragment>
        <div className="pageContent">
            <p className="fullDetails"><b>Privacy Policy:</b><br />
            Our website does not store any user data. Any data entered or generated by the user is only held in memory during encryption or decryption and is not permanently stored.</p>
        </div>
        <Link to="/">To homepage</Link>
    </React.Fragment>
}